### PR TITLE
feature: add name formatter

### PR DESCRIPTION
**Pull request by akinsho**
This PR adds the ability to format the name a buffer is given in the bufferline. It is intended to potentially make otherwise confusing names clearer or for minor tweaks to naming.

It is not intended as a way for users to use full paths as names or inject highlighting etc. If users use it for such it will break, and I will not fix that 🤷🏾‍♂️ .

The key can be specified as
```lua
--- NOTE that if nil is returned the default will be used anyway
name_formatter = function(default_name, path)
  if condition then
    return <new-name>
  end
end
```

### Todo
- [x] Tests
- [x] Sterner wording/warning docs

### CODE REVIEW

**Comment by akinsho** [comment]
@pwntester can you give this a try to see if it fits your use case?

**Comment by akinsho** [comment]
fixes #130

**Comment by pwntester** [comment]
Thanks for implementing this and for doing it so fast!

Im using it like this:

```lua
      name_formatter = function(_, path)
        local bufnr = vim.fn.bufnr(path)
        if vim.startswith(path, "octo:") and octo_buffers and octo_buffers[bufnr] then
          local title = octo_buffers[bufnr].node.title
          return string.sub(title, 1, 10)
        end
      end,
```

Not sure if I can always trust the output of `vim.fn.bufnr(path)` though. Can you pass the bufnr as well?

**Comment by akinsho** [comment]
@pwntester I've tweaked this now so that the function returns a table containing a `name`, `path` and `bufnr`. Let me know if that works for you and I'll tidy this up and merge it.

**Comment by pwntester** [comment]
Awesome, thanks! works like a charm!

**Pull request merged**
