### PR TITLE
fix: hide bufferline on start if not configured

### PR DESCRIPTION
**Pull request by akinsho**
This PR changes startup to only show the bufferline on startup if a user has configured it to show up

@Pocco81 please try this to see if it fixes the issue.

### CODE REVIEW

**Comment by akinsho** [comment]
should fix #146

**Comment by akinsho** [comment]
@Pocco81 I don't see any bufferline when I use this PR using dashboard. If you are using packer, did you make sure to reload the config or restart your neovim?

**Comment by Pocco81** [comment]
Whoops! My bad! since the change in this PR was just one line I simply copy and pasted it locally. Turns out I pasted it in the wrong place. Yes, now everything works :)

**Comment by akinsho** [comment]
@Pocco81 I thought of a bug so just repushed a new solution, can you cross-check it still works for you and if so I'll merge it.

**Comment by Pocco81** [comment]
Yep, it works as well. Also, I noticed that you call `vim.cmd` and `vim.o` a lot of times. Maybe you should consider instantiate both like you did with `vim.fn` for example? (I mean: `local cmd = vim.cmd). That would make the code more readable :+1:

**Pull request merged**
